---
natd_interface: em0

switches:
  - name: sw0
    inet: 192.168.10.84/24

  - name: sw1
    type: manual
    interface: bridge1
  
  - name: sw2
    inet: 192.168.2.84/24
  - name: sw3
    inet: 192.168.3.84/24
  - name: sw4
    inet: 192.168.4.84/24

